CREATE DATABASE IF NOT EXISTS codesmic CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE codesmic;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL,
  institution VARCHAR(100) NOT NULL,
  join_date VARCHAR(50) NOT NULL,
  xp INT NOT NULL DEFAULT 0,
  level INT NOT NULL DEFAULT 1,
  challenges_completed INT NOT NULL DEFAULT 0,
  projects_completed INT NOT NULL DEFAULT 0,
  rank VARCHAR(100) NOT NULL DEFAULT 'Rookie Star'
);

CREATE TABLE IF NOT EXISTS activities (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  xp INT NOT NULL DEFAULT 0,
  type VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS questions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  xp INT NOT NULL DEFAULT 10,
  subject VARCHAR(100) NOT NULL,
  subtopic VARCHAR(100) NOT NULL,
  difficulty VARCHAR(50) NOT NULL,
  type VARCHAR(50) NOT NULL DEFAULT 'Fix & Run Lab',
  mini_materi TEXT NOT NULL,
  code_html TEXT NOT NULL,
  code_css TEXT NOT NULL,
  code_js TEXT NOT NULL,
  task TEXT NOT NULL,
  validation_js TEXT NOT NULL,
  answer TEXT NOT NULL,
  hint1 TEXT NOT NULL,
  hint2 TEXT NOT NULL,
  hint3 TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO questions (
  title, xp, subject, subtopic, difficulty, type,
  mini_materi, code_html, code_css, code_js,
  task, validation_js, answer, hint1, hint2, hint3
) VALUES

-- ================= HTML (15) =================

('DOCTYPE HTML',10,'HTML','Struktur Dasar HTML','Mudah','Fix & Run Lab',
'DOCTYPE wajib di awal HTML.',
'<html><body></body></html>','','',
'Tambahkan DOCTYPE.',
'document.doctype && document.doctype.name==="html"',
'Di atas file.','HTML5.','<!DOCTYPE html>'),

('Tag Title',10,'HTML','Head','Mudah','Fix & Run Lab',
'title untuk judul tab.',
'<head></head>','','',
'Tambahkan title "Web".',
'document.querySelector("title") && document.title==="Web"',
'Di head.','Judul tab.','<title>Web</title>'),

('Heading H1',10,'HTML','Teks','Mudah','Fix & Run Lab',
'h1 untuk judul.',
'<p>Judul</p>','','',
'Ubah jadi h1.',
'document.querySelector("h1")!==null',
'Gunakan h1.','Besar.','<h1>'),

('Paragraf',10,'HTML','Teks','Mudah','Fix & Run Lab',
'p untuk paragraf.',
'<h1>Halo</h1>','','',
'Tambah paragraf.',
'document.querySelector("p")!==null',
'Tag p.','Tambahkan teks.','<p>'),

('Bold Text',10,'HTML','Formatting','Mudah','Fix & Run Lab',
'b/strong tebal.',
'<p>HTML penting</p>','','',
'Tebalkan HTML.',
'document.querySelector("b,strong")!==null',
'Gunakan b.','Atau strong.','<b>'),

('Link',10,'HTML','Link','Mudah','Fix & Run Lab',
'a untuk link.',
'<p>Klik</p>','','',
'Buat link ke google.',
'document.querySelector("a") && document.querySelector("a").href.includes("google")',
'Gunakan a.','Tambahkan href.','https://google.com'),

('Image',10,'HTML','Media','Mudah','Fix & Run Lab',
'img untuk gambar.',
'<h1>Galeri</h1>','','',
'Tambahkan img.',
'document.querySelector("img")!==null',
'Gunakan img.','Tanpa penutup.','src'),

('List',10,'HTML','List','Mudah','Fix & Run Lab',
'ul li list.',
'<h2>Hobi</h2>','','',
'Buat 2 item.',
'document.querySelectorAll("li").length>=2',
'ul.','li.','2 item'),

('Table Row',10,'HTML','Table','Sedang','Fix & Run Lab',
'tr baris.',
'<table></table>','','',
'Tambah 1 baris.',
'document.querySelector("tr")!==null',
'tr.','td.','row'),

('Table Header',10,'HTML','Table','Sedang','Fix & Run Lab',
'th header.',
'<table></table>','','',
'Tambah th.',
'document.querySelector("th")!==null',
'th.','atas.','header'),

('Form Input',10,'HTML','Form','Sedang','Fix & Run Lab',
'input text.',
'<form></form>','','',
'Tambah input text.',
'document.querySelector("input[type=text]")!==null',
'input.','type.','text'),

('Radio',10,'HTML','Form','Sedang','Fix & Run Lab',
'radio.',
'<form></form>','','',
'2 radio.',
'document.querySelectorAll("input[type=radio]").length>=2',
'radio.','2.','name'),

('Select',10,'HTML','Form','Sedang','Fix & Run Lab',
'select option.',
'<form></form>','','',
'Tambah select.',
'document.querySelector("select")!==null',
'select.','option.','dropdown'),

('Semantic',10,'HTML','Semantic','Sulit','Fix & Run Lab',
'header main footer.',
'<div>Isi</div>','','',
'Gunakan header dan main.',
'document.querySelector("header") && document.querySelector("main")',
'Semantic.','header.','main'),

('Iframe',10,'HTML','Media','Sulit','Fix & Run Lab',
'iframe embed.',
'<h2>Video</h2>','','',
'Tambahkan iframe.',
'document.querySelector("iframe")!==null',
'iframe.','embed.','youtube'),

-- ================= CSS (12) =================

('Color',10,'CSS','Dasar','Mudah','Fix & Run Lab',
'color teks.',
'<p id="t">Teks</p>','#t{}','',
'Merah.',
'getComputedStyle(document.querySelector("#t")).color==="rgb(255, 0, 0)"',
'color.','red.',';'),

('Background',10,'CSS','Dasar','Mudah','Fix & Run Lab',
'background.',
'<body></body>','body{}','',
'Biru.',
'getComputedStyle(document.body).backgroundColor==="rgb(0, 0, 255)"',
'background.','blue.',';'),

('Font Size',10,'CSS','Teks','Mudah','Fix & Run Lab',
'font size.',
'<p>Halo</p>','p{}','',
'20px.',
'getComputedStyle(document.querySelector("p")).fontSize==="20px"',
'font-size.','px.','20'),

('Margin',10,'CSS','Box','Mudah','Fix & Run Lab',
'margin.',
'<div id="a"></div>','#a{}','',
'10px.',
'getComputedStyle(document.querySelector("#a")).marginTop==="10px"',
'margin.','luar.','10'),

('Padding',10,'CSS','Box','Mudah','Fix & Run Lab',
'padding.',
'<div id="a"></div>','#a{}','',
'10px.',
'getComputedStyle(document.querySelector("#a")).paddingTop==="10px"',
'padding.','dalam.','10'),

('Border',10,'CSS','Box','Mudah','Fix & Run Lab',
'border.',
'<div id="a"></div>','#a{}','',
'solid.',
'getComputedStyle(document.querySelector("#a")).borderStyle==="solid"',
'border.','solid.','1px'),

('Flex',10,'CSS','Layout','Sedang','Fix & Run Lab',
'flex.',
'<div class="c"></div>','.c{}','',
'flex.',
'getComputedStyle(document.querySelector(".c")).display==="flex"',
'display.','flex.',';'),

('Justify Center',10,'CSS','Flex','Sedang','Fix & Run Lab',
'center.',
'<div class="c"></div>','.c{display:flex;}','',
'center.',
'getComputedStyle(document.querySelector(".c")).justifyContent==="center"',
'justify.','center.',';'),

('Align Center',10,'CSS','Flex','Sedang','Fix & Run Lab',
'align.',
'<div class="c"></div>','.c{display:flex;}','',
'center.',
'getComputedStyle(document.querySelector(".c")).alignItems==="center"',
'align.','center.',';'),

('Hover',10,'CSS','Effect','Sedang','Fix & Run Lab',
'hover.',
'<button>klik</button>','','',
'hover warna.',
'document.styleSheets.length>0',
':hover.','pseudo.','effect'),

('Grid',10,'CSS','Layout','Sulit','Fix & Run Lab',
'grid.',
'<div class="g"></div>','.g{}','',
'grid.',
'getComputedStyle(document.querySelector(".g")).display==="grid"',
'display.','grid.',';'),

('Shadow',10,'CSS','Effect','Sulit','Fix & Run Lab',
'shadow.',
'<div></div>','div{}','',
'box-shadow.',
'getComputedStyle(document.querySelector("div")).boxShadow!=="none"',
'shadow.','effect.','css'),

-- ================= JS (12) =================

('Console Log',10,'JS','Output','Mudah','Fix & Run Lab',
'console.',
'','','',
'Tampilkan Hello.',
'consoleOutput.includes("Hello")',
'console.','log.','Hello'),

('Variabel',10,'JS','Dasar','Mudah','Fix & Run Lab',
'let.',
'','','',
'let nama="Andi".',
'typeof nama!=="undefined" && nama==="Andi"',
'let.','variable.','string'),

('InnerText',10,'JS','DOM','Mudah','Fix & Run Lab',
'innerText.',
'<h1 id="j"></h1>','','',
'Isi teks.',
'document.querySelector("#j").innerText!==""',
'query.','innerText.','='),

('Alert',10,'JS','Output','Mudah','Fix & Run Lab',
'alert.',
'','','',
'Tampilkan alert.',
'alertCalled===true',
'alert.','popup.','()'),

('If Else',10,'JS','Logic','Sedang','Fix & Run Lab',
'if.',
'','','let nilai=80;',
'Jika >=75 tampilkan Lulus.',
'consoleOutput.includes("Lulus")',
'if.','>=.','log'),

('Loop',10,'JS','Loop','Sedang','Fix & Run Lab',
'for.',
'','','',
'Loop 1-3.',
'consoleOutput.includes("3")',
'for.','i.','++'),

('Function',10,'JS','Function','Sedang','Fix & Run Lab',
'function.',
'','','',
'Buat sapa.',
'typeof sapa==="function"',
'function.','nama.','()'),

('Event Click',10,'JS','Event','Sedang','Fix & Run Lab',
'event.',
'<button id="b"></button>','','',
'Klik tampil teks.',
'document.querySelector("#b").onclick!==null',
'event.','click.','onclick'),

('Input Value',10,'JS','DOM','Sedang','Fix & Run Lab',
'value.',
'<input id="n">','','',
'Ambil value.',
'document.querySelector("#n").value!==undefined',
'value.','input.','id'),

('Array',10,'JS','Array','Sulit','Fix & Run Lab',
'array.',
'','','',
'Buat array.',
'Array.isArray(buah)',
'[].','data.','array'),

('setTimeout',10,'JS','Timing','Sulit','Fix & Run Lab',
'timeout.',
'','','',
'Delay.',
'typeof setTimeout==="function"',
'timeout.','delay.','1000'),

('Style JS',10,'JS','DOM','Sulit','Fix & Run Lab',
'style.',
'<p id="t"></p>','','',
'Ubah warna.',
'document.querySelector("#t").style.color!==""',
'style.','color.','red'),

-- ================= FRAMEWORK (11) =================

('CDN Bootstrap',10,'Framework','CDN','Mudah','Fix & Run Lab',
'cdn bootstrap.',
'<head></head>','','',
'Tambah CDN.',
'document.querySelector("link[href*=\"bootstrap\"]")',
'link.','cdn.','bootstrap'),

('Container',10,'Framework','Layout','Mudah','Fix & Run Lab',
'container.',
'<div></div>','','',
'Gunakan container.',
'document.querySelector(".container")',
'class.','container.','bootstrap'),

('Row Col',10,'Framework','Grid','Sedang','Fix & Run Lab',
'grid.',
'<div class="container"></div>','','',
'2 col.',
'document.querySelectorAll("[class*=col]").length>=2',
'row.','col.','grid'),

('Button',10,'Framework','Component','Mudah','Fix & Run Lab',
'btn.',
'<button>klik</button>','','',
'btn bootstrap.',
'document.querySelector(".btn")',
'btn.','primary.','class'),

('Card',10,'Framework','Component','Sedang','Fix & Run Lab',
'card.',
'<div></div>','','',
'card.',
'document.querySelector(".card")',
'card.','body.','component'),

('Navbar',10,'Framework','Component','Sedang','Fix & Run Lab',
'navbar.',
'<div></div>','','',
'navbar.',
'document.querySelector(".navbar")',
'navbar.','nav.','menu'),

('Responsive Col',10,'Framework','Responsive','Sedang','Fix & Run Lab',
'col-md.',
'<div class="row"></div>','','',
'col-md.',
'document.querySelector("[class*=col-md]")',
'md.','responsive.','grid'),

('Margin Utility',10,'Framework','Utility','Mudah','Fix & Run Lab',
'mt.',
'<div></div>','','',
'mt-3.',
'document.querySelector("[class*=mt-]")',
'mt.','margin.','bootstrap'),

('Padding Utility',10,'Framework','Utility','Mudah','Fix & Run Lab',
'padding.',
'<div></div>','','',
'p-3.',
'document.querySelector("[class*=p-]")',
'p.','padding.','class'),

('Text Center',10,'Framework','Utility','Mudah','Fix & Run Lab',
'text-center.',
'<p></p>','','',
'center.',
'document.querySelector(".text-center")',
'text.','center.','class'),

('Color Utility',10,'Framework','Utility','Sedang','Fix & Run Lab',
'warna.',
'<p></p>','','',
'text-primary.',
'document.querySelector("[class*=text-]")',
'color.','class.','bootstrap'),

-- ================= UI/UX (10) =================

('Konsistensi Warna',10,'UI/UX','UI','Mudah','Fix & Run Lab',
'warna konsisten.',
'<h1 style="color:red"></h1><p style="color:blue"></p>','','',
'samakan warna.',
'getComputedStyle(document.querySelector("h1")).color===getComputedStyle(document.querySelector("p")).color',
'warna.','konsisten.','sama'),

('Typography',10,'UI/UX','UI','Mudah','Fix & Run Lab',
'font.',
'<p>teks</p>','p{}','',
'font.',
'getComputedStyle(document.querySelector("p")).fontFamily!==""',
'font.','family.','readable'),

('Alignment',10,'UI/UX','Prinsip','Mudah','Fix & Run Lab',
'align.',
'<h1>judul</h1>','h1{}','',
'center.',
'getComputedStyle(document.querySelector("h1")).textAlign==="center"',
'align.','center.','css'),

('Contrast',10,'UI/UX','Prinsip','Mudah','Fix & Run Lab',
'kontras.',
'<div style="background:white;color:white">text</div>','','',
'perbaiki.',
'getComputedStyle(document.querySelector("div")).color!=="rgb(255, 255, 255)"',
'warna.','beda.','contrast'),

('Whitespace',10,'UI/UX','Prinsip','Mudah','Fix & Run Lab',
'spacing.',
'<p>a</p><p>b</p>','p{}','',
'jarak.',
'getComputedStyle(document.querySelector("p")).marginBottom!=="0px"',
'margin.','space.','layout'),

('Navigasi',10,'UI/UX','UX','Sedang','Fix & Run Lab',
'navigasi.',
'<div>Home</div>','','',
'link.',
'document.querySelectorAll("a").length>=1',
'a.','menu.','nav'),

('Button UX',10,'UI/UX','UX','Sedang','Fix & Run Lab',
'button jelas.',
'<button style="color:red;background:red">klik</button>','','',
'perbaiki.',
'getComputedStyle(document.querySelector("button")).color!=="rgb(255, 0, 0)"',
'kontras.','ux.','warna'),

('Readable Text',10,'UI/UX','UX','Sedang','Fix & Run Lab',
'readable.',
'<p style="font-size:8px">text</p>','','',
'perbesar.',
'parseInt(getComputedStyle(document.querySelector("p")).fontSize)>=14',
'font.','size.','14'),

('Responsive',10,'UI/UX','Responsive','Sulit','Fix & Run Lab',
'responsive.',
'','','',
'media query.',
'document.styleSheets.length>0',
'@media.','responsive.','mobile'),

('Hierarchy',10,'UI/UX','Prinsip','Sulit','Fix & Run Lab',
'hierarchy.',
'<h3>judul</h3>','','',
'jadikan utama.',
'document.querySelector("h1")!==null',
'h1.','utama.','besar');

-- =========================
-- LEVEL MUDAH (15)
-- =========================

('Halaman Kosong',20,'HTML','Struktur Dasar HTML','Mudah','Code Challenge',
'Kenapa halaman kosong?',
'<!DOCTYPE html><html><head><title></title></head><body></body></html>','','',
'Isi title "Belajar Web" dan tampilkan h1 "Halo Dunia"',
'const t=document.querySelector("title");const h=document.querySelector("h1");return t&&h;',
'Cek title','Gunakan h1','Isi title dan tambah h1'),

('Teks Tidak Rapi',20,'HTML','Teks','Mudah','Code Challenge',
'Kenapa teks tidak terstruktur?',
'<body>Belajar HTML</body>','','',
'Buat h1 dan paragraf',
'return document.querySelector("h1")&&document.querySelector("p");',
'Gunakan h1','Gunakan p','Pisahkan teks'),

('Link Mati',20,'HTML','Link','Mudah','Code Challenge',
'Kenapa link tidak jalan?',
'<body>Klik</body>','','',
'Buat link ke google',
'return document.querySelector("a");',
'Gunakan a','Tambahkan href','Isi URL'),

('Gambar Hilang',20,'HTML','Media','Mudah','Code Challenge',
'Kenapa gambar tidak muncul?',
'<body></body>','','',
'Tampilkan img image.jpg',
'return document.querySelector("img");',
'Gunakan img','Tambahkan src','Isi image.jpg'),

('List Berantakan',20,'HTML','List','Mudah','Code Challenge',
'Kenapa data tidak rapi?',
'<body>Ayam Nasi Teh</body>','','',
'Buat list',
'return document.querySelector("ul");',
'Gunakan ul','Gunakan li','Pisahkan item'),

('Tabel Kosong',20,'HTML','Tabel','Mudah','Code Challenge',
'Kenapa tabel tidak ada?',
'<body></body>','','',
'Buat tabel 2 kolom',
'return document.querySelector("table");',
'Gunakan table','Gunakan tr td','Isi data'),

('Form Tidak Input',20,'HTML','Form','Mudah','Code Challenge',
'Kenapa tidak bisa input?',
'<form></form>','','',
'Tambah input text',
'return document.querySelector("input");',
'Gunakan input','Type text','Letakkan di form'),

('Warna Polos',20,'CSS','Dasar CSS','Mudah','Code Challenge',
'Kenapa tidak ada warna?',
'<p>Halo</p>','p{}','',
'Buat teks merah',
'return true;',
'Gunakan color','Isi red','Tambahkan di CSS'),

('Font Kecil',20,'CSS','Font','Mudah','Code Challenge',
'Kenapa teks kecil?',
'<p>Halo</p>','p{}','',
'Perbesar font',
'return true;',
'Gunakan font-size','Isi ukuran','Tambahkan CSS'),

('Selector Gagal',20,'CSS','Selector','Mudah','Code Challenge',
'Kenapa style tidak masuk?',
'<p class="a">Hi</p>','.a{}','',
'Tambahkan warna',
'return true;',
'Gunakan .a','Tambah property','Gunakan color'),

('Margin Mepet',20,'CSS','Box Model','Mudah','Code Challenge',
'Kenapa mepet?',
'<div>Box</div>','div{}','',
'Tambahkan margin',
'return true;',
'Gunakan margin','Isi px','Tambahkan CSS'),

('JS Alert',20,'JavaScript','Output','Mudah','Code Challenge',
'Kenapa tidak muncul?',
'','','',
'Tampilkan alert Halo',
'return true;',
'Gunakan alert','Isi teks','alert("Halo")'),

('JS Variabel',20,'JavaScript','Variabel','Mudah','Code Challenge',
'Kenapa data tidak tersimpan?',
'','','',
'Buat variabel nama',
'return true;',
'Gunakan let','Isi nama','let nama'),

('JS Button',20,'JavaScript','Event','Mudah','Code Challenge',
'Kenapa tidak klik?',
'<button>Click</button>','','',
'Tambahkan onclick',
'return true;',
'Gunakan onclick','Isi fungsi','Tambahkan event'),

('Input Value',20,'JavaScript','DOM','Mudah','Code Challenge',
'Kenapa input kosong?',
'<input id="i">','','',
'Ambil value input',
'return true;',
'Gunakan value','Ambil id','Gunakan DOM'),

-- =========================
-- LEVEL SEDANG (20)
-- =========================

('Layout Semantic',20,'HTML','Semantic','Sedang','Code Challenge',
'Kenapa layout kacau?',
'<body></body>','','',
'Buat header main footer',
'return document.querySelector("header");',
'Gunakan semantic','Tambah header','Tambah footer'),

('Form Email',20,'HTML','Form','Sedang','Code Challenge',
'Kenapa tidak valid?',
'<form></form>','','',
'Tambah email',
'return document.querySelector("input[type=email]");',
'Gunakan email','Type email','Tambahkan'),

('Tabel Lengkap',20,'HTML','Tabel','Sedang','Code Challenge',
'Kenapa tidak rapi?',
'<body></body>','','',
'Tambah thead tbody',
'return true;',
'Gunakan thead','Gunakan tbody','Isi data'),

('Video Error',20,'HTML','Media','Sedang','Code Challenge',
'Kenapa video tidak tampil?',
'<body></body>','','',
'Tambah video',
'return document.querySelector("video");',
'Gunakan video','Tambahkan src','Isi file'),

('Label Tidak Terhubung',20,'HTML','Form','Sedang','Code Challenge',
'Kenapa label tidak klik?',
'<label>Nama</label><input>','','',
'Hubungkan label',
'return true;',
'Gunakan for','Samakan id','Hubungkan'),

('Background Image',20,'CSS','Background','Sedang','Code Challenge',
'Kenapa kosong?',
'<div></div>','div{}','',
'Tambah background image',
'return true;',
'Gunakan background-image','Isi url','Tambahkan'),

('Border Tidak Ada',20,'CSS','Box','Sedang','Code Challenge',
'Kenapa box tidak terlihat?',
'<div></div>','div{}','',
'Tambah border',
'return true;',
'Gunakan border','Isi px','Tambahkan'),

('Flex Gagal',20,'CSS','Flexbox','Sedang','Code Challenge',
'Kenapa tidak sejajar?',
'<div class="c"><div></div><div></div></div>','.c{}','',
'Gunakan flex',
'return true;',
'Gunakan display flex','Tambahkan','Atur arah'),

('Hover Mati',20,'CSS','Effect','Sedang','Code Challenge',
'Kenapa tidak berubah?',
'<button>Click</button>','button{}','',
'Tambah hover',
'return true;',
'Gunakan :hover','Tambahkan','Ubah warna'),

('Center Gagal',20,'CSS','Layout','Sedang','Code Challenge',
'Kenapa tidak center?',
'<div></div>','div{}','',
'Center div',
'return true;',
'Gunakan flex','Gunakan center','Atur justify'),

('Overflow Rusak',20,'CSS','Layout','Sedang','Code Challenge',
'Kenapa keluar?',
'<div style="height:50px">text panjang</div>','div{}','',
'Atur overflow',
'return true;',
'Gunakan overflow','Hidden/scroll','Tambahkan'),

('Box Model Error',20,'CSS','Box Model','Sedang','Code Challenge',
'Kenapa ukuran salah?',
'<div></div>','div{}','',
'Perbaiki padding',
'return true;',
'Gunakan padding','Isi px','Tambahkan'),

('Login IF',20,'JavaScript','Percabangan','Sedang','Code Challenge',
'Kenapa gagal?',
'','','',
'Gunakan if login',
'return true;',
'Gunakan if','Bandingkan','Tambahkan'),

('Loop Data',20,'JavaScript','Loop','Sedang','Code Challenge',
'Kenapa tidak semua tampil?',
'','','',
'Gunakan for',
'return true;',
'Gunakan for','Loop data','Tambahkan'),

('Function Hitung',20,'JavaScript','Function','Sedang','Code Challenge',
'Kenapa berulang?',
'','','',
'Buat function',
'return true;',
'Gunakan function','Tambah return','Isi parameter'),

('DOM Update',20,'JavaScript','DOM','Sedang','Code Challenge',
'Kenapa tidak berubah?',
'<p id="t"></p>','','',
'Ubah teks',
'return true;',
'Gunakan getElementById','Ubah innerText','Tambahkan'),

('Array Push',20,'JavaScript','Array','Sedang','Code Challenge',
'Kenapa tidak bertambah?',
'','','',
'Tambah data',
'return true;',
'Gunakan push','Tambah item','Gunakan array'),

('Event Listener',20,'JavaScript','Event','Sedang','Code Challenge',
'Kenapa tidak jalan?',
'<button id="b"></button>','','',
'Gunakan addEventListener',
'return true;',
'Gunakan event','Tambahkan listener','Klik'),

('Bootstrap CDN',20,'Framework','Bootstrap','Sedang','Code Challenge',
'Kenapa bootstrap mati?',
'<head></head>','','',
'Tambahkan CDN',
'return true;',
'Gunakan link','Ambil CDN','Tambahkan'),

('Navbar UI',20,'UI/UX','Navigation','Sedang','Code Challenge',
'Kenapa bingung?',
'<body></body>','','',
'Buat navbar',
'return true;',
'Gunakan nav','Tambah menu','Struktur'),

-- =========================
-- LEVEL SULIT (10)
-- =========================

('Landing Page Rusak',20,'HTML+CSS','Layout','Sulit','Code Challenge',
'Kenapa rusak?',
'<body></body>','','',
'Perbaiki layout',
'return true;',
'Gunakan struktur','Tambah CSS','Perbaiki'),

('Grid Kompleks',20,'CSS','Grid','Sulit','Code Challenge',
'Kenapa tidak rapi?',
'<div></div>','div{}','',
'Gunakan grid',
'return true;',
'Gunakan grid','Atur kolom','Tambahkan'),

('Animasi Tombol',20,'CSS','Animation','Sulit','Code Challenge',
'Kenapa tidak animasi?',
'<button></button>','button{}','',
'Tambah animasi',
'return true;',
'Gunakan keyframes','Tambah animasi','Gunakan'),

('Form Validation',20,'JavaScript','Validation','Sulit','Code Challenge',
'Kenapa bebas submit?',
'','','',
'Validasi input kosong',
'return true;',
'Gunakan if','Cek value','Tambahkan'),

('Filter Nilai',20,'JavaScript','Array','Sulit','Code Challenge',
'Kenapa tidak filter?',
'','','',
'Filter >75',
'return true;',
'Gunakan filter','Bandingkan','Return'),

('Jam Digital',20,'JavaScript','Timing','Sulit','Code Challenge',
'Kenapa tidak update?',
'<p id="jam"></p>','','',
'Buat jam',
'return true;',
'Gunakan setInterval','Gunakan Date','Update'),

('Object Siswa',20,'JavaScript','Object','Sulit','Code Challenge',
'Kenapa tidak rapi?',
'','','',
'Buat object',
'return true;',
'Gunakan key','Value','Object'),

('Class User',20,'JavaScript','Class','Sulit','Code Challenge',
'Kenapa kompleks?',
'','','',
'Buat class',
'return true;',
'Gunakan class','Constructor','this'),

('Responsive HP',20,'CSS','Responsive','Sulit','Code Challenge',
'Kenapa rusak?',
'<div></div>','div{}','',
'Gunakan media query',
'return true;',
'Gunakan media','Atur ukuran','Responsive'),

('UI Redesign',20,'UI/UX','Design','Sulit','Code Challenge',
'Kenapa jelek?',
'<body></body>','','',
'Perbaiki UI',
'return true;',
'Gunakan warna','Layout','Perbaiki');

-- ================= HTML =================
('Struktur HTML Salah',25,'HTML','Struktur Dasar HTML','Mudah','Debugging Zone',
'Struktur HTML harus html > head > body.',
'<!DOCTYPE html><html><head><title>Web</title><body><h1>Halo</h1></head></body></html>','','',
'Perbaiki struktur HTML.',
'return document.body && document.head && document.body.parentElement===document.documentElement;',
'Urutan salah','body di dalam head','pindahkan body keluar head'),

('Tag Tidak Ditutup',25,'HTML','Teks','Mudah','Debugging Zone',
'Tag HTML harus ditutup.',
'<p>Halo dunia','','',
'Perbaiki tag.',
'return document.querySelector("p")!==null;',
'Butuh pasangan','closing tag','</p>'),

('Heading Salah',25,'HTML','Teks','Mudah','Debugging Zone',
'Heading hanya h1-h6.',
'<h7>Judul</h7>','','',
'Perbaiki heading.',
'return document.querySelector("h1,h2,h3,h4,h5,h6")!==null;',
'Tidak ada h7','gunakan h1-h6','<h1>'),

('Link Error',25,'HTML','Link','Mudah','Debugging Zone',
'Link eksternal butuh https://',
'<a href="google.com">Google</a>','','',
'Perbaiki link.',
'return document.querySelector("a").href.startsWith("http");',
'butuh protokol','https','https://'),

('Img Tanpa Alt',25,'HTML','Media','Mudah','Debugging Zone',
'Alt penting.',
'<img src="a.jpg">','','',
'Tambahkan alt.',
'return document.querySelector("img").hasAttribute("alt");',
'aksesibilitas','pakai alt','alt=""'),

('List Salah',25,'HTML','List','Sedang','Debugging Zone',
'List pakai li.',
'<ul><p>Item</p></ul>','','',
'Perbaiki list.',
'return document.querySelector("li")!==null;',
'bukan p','li','<li>'),

('Table Tanpa TR',25,'HTML','Tabel','Sedang','Debugging Zone',
'Table butuh tr.',
'<table><td>Data</td></table>','','',
'Perbaiki table.',
'return document.querySelector("tr")!==null;',
'baris','tr','<tr>'),

('Form Tanpa Submit',25,'HTML','Form','Sedang','Debugging Zone',
'Form butuh submit.',
'<form><input></form>','','',
'Perbaiki form.',
'return document.querySelector("button,input[type=submit]")!==null;',
'tombol','submit','button'),

-- ================= CSS =================
('CSS Syntax Salah',25,'CSS','Dasar','Mudah','Debugging Zone',
'CSS pakai : dan ;',
'','p { color red }','',
'Perbaiki CSS.',
'return true;',
'kurang simbol',': dan ;','color: red;'),

('Selector Salah',25,'CSS','Selector','Mudah','Debugging Zone',
'Class pakai titik.',
'<h1 class="judul">Halo</h1>','#judul{color:blue;}','',
'Perbaiki selector.',
'return true;',
'class vs id','.','.judul'),

('Typo Property',25,'CSS','Teks','Mudah','Debugging Zone',
'Property harus benar.',
'','p{fontz-size:20px;}','',
'Perbaiki property.',
'return true;',
'typo','font-size','perbaiki'),

('Margin Tanpa Satuan',25,'CSS','Box Model','Sedang','Debugging Zone',
'Butuh px.',
'','div{margin:10;}','',
'Perbaiki margin.',
'return true;',
'butuh satuan','px','10px'),

('Flex Tidak Aktif',25,'CSS','Flexbox','Sedang','Debugging Zone',
'display:flex wajib.',
'','.c{justify-content:center;}','',
'Perbaiki flex.',
'return true;',
'kurang display','flex','display:flex'),

('Hover Salah',25,'CSS','Interaksi','Sedang','Debugging Zone',
'hover pakai :',
'','button hover{color:red;}','',
'Perbaiki hover.',
'return true;',
'pakai :','pseudo',':hover'),

('Background Tanpa ;',25,'CSS','Background','Sedang','Debugging Zone',
'akhiri ;',
'','div{background:red}','',
'Perbaiki syntax.',
'return true;',
'; hilang','akhiri ;',';'),

('Display Salah',25,'CSS','Layout','Sulit','Debugging Zone',
'display mempengaruhi layout.',
'','span{display:block;}','',
'Analisis & perbaiki sesuai inline.',
'return true;',
'span inline','block beda','inline'),

-- ================= JS =================
('Const Error',25,'JavaScript','Variabel','Mudah','Debugging Zone',
'const tidak bisa diubah.',
'','','const a=5;a=10;',
'Perbaiki variabel.',
'return true;',
'const fix','pakai let','let'),

('Console Typo',25,'JavaScript','Output','Mudah','Debugging Zone',
'console.log harus benar.',
'','','consol.log("Hi")',
'Perbaiki console.',
'return true;',
'typo','console','console.log'),

('If Salah',25,'JavaScript','Percabangan','Sedang','Debugging Zone',
'if butuh ().',
'','','if x>5 {console.log(x)}',
'Perbaiki if.',
'return true;',
'kurang ()','syntax','if(x>5)'),

('Loop Error',25,'JavaScript','Loop','Sedang','Debugging Zone',
'for pakai ;',
'','','for(let i=0 i<5 i++){}',
'Perbaiki loop.',
'return true;',
'; kurang','for',';;'),

('Function Tanpa Return',25,'JavaScript','Function','Sedang','Debugging Zone',
'return diperlukan.',
'','','function t(a,b){a+b;}',
'Perbaiki function.',
'return true;',
'tidak return','pakai return','return a+b'),

('DOM Salah ID',25,'JavaScript','DOM','Sedang','Debugging Zone',
'ID harus sama.',
'<h1 id="title">Hi</h1>','','document.getElementById("judul")',
'Perbaiki ID.',
'return true;',
'beda id','cek html','title'),

('Array Typo',25,'JavaScript','Array','Sedang','Debugging Zone',
'method harus benar.',
'','','arr.puch(1)',
'Perbaiki array.',
'return true;',
'typo','push','push'),

('JSON Error',25,'JavaScript','JSON','Sulit','Debugging Zone',
'JSON harus string.',
'','','JSON.parse({a:1})',
'Perbaiki JSON.',
'return true;',
'harus string','gunakan ""','"{a:1}"'),

('Try Tanpa Catch',25,'JavaScript','Error Handling','Sulit','Debugging Zone',
'try butuh catch.',
'','','try{console.log(x)}',
'Perbaiki error handling.',
'return true;',
'kurang catch','tambahkan catch','catch(e)'),

('Event Tidak Jalan',25,'JavaScript','Event','Sulit','Debugging Zone',
'event butuh elemen.',
'','','button.onclick=klik;',
'Perbaiki event.',
'return true;',
'button undefined','querySelector','ambil element'),

-- ================= FRAMEWORK =================
('CDN Salah',25,'Framework','CDN','Mudah','Debugging Zone',
'link butuh rel.',
'<link href="bootstrap.css">','','',
'Perbaiki CDN.',
'return true;',
'rel hilang','stylesheet','rel="stylesheet"'),

('Class Typo',25,'Framework','Component','Mudah','Debugging Zone',
'class harus benar.',
'<button class="btn btn-primmary">','','',
'Perbaiki class.',
'return true;',
'typo','primary','btn-primary'),

('Grid Salah',25,'Framework','Grid','Sedang','Debugging Zone',
'grid max 12.',
'<div class="col-8"></div><div class="col-8"></div>','','',
'Perbaiki grid.',
'return true;',
'>12','max 12','ubah'),

('Container Hilang',25,'Framework','Layout','Sedang','Debugging Zone',
'butuh container.',
'<div class="row"></div>','','',
'Perbaiki struktur.',
'return true;',
'kurang container','bootstrap','tambahkan'),

-- ================= UI/UX =================
('Warna Tidak Kontras',25,'UI/UX','UI','Mudah','Debugging Zone',
'kontras penting.','','','',
'Perbaiki warna.','return true;',
'terlalu mirip','kontras','ubah warna'),

('Font Terlalu Kecil',25,'UI/UX','UX','Mudah','Debugging Zone',
'readability penting.','','','',
'Perbaiki font.','return true;',
'kecil','perbesar','font-size'),

('Navigasi Duplikat',25,'UI/UX','UX','Sedang','Debugging Zone',
'menu harus jelas.','','','',
'Perbaiki navigasi.','return true;',
'sama semua','bingung','beda'),

('Tidak Responsive',25,'UI/UX','Responsive','Sedang','Debugging Zone',
'responsive penting.','','','',
'Perbaiki layout.','return true;',
'mobile rusak','responsive','media query'),

('Layout Berantakan',25,'UI/UX','Layout','Sulit','Debugging Zone',
'alignment penting.','','','',
'Perbaiki layout.','return true;',
'tidak rapi','grid/flex','rapikan'),

('Button Terlalu Kecil',25,'UI/UX','UX','Sedang','Debugging Zone',
'button harus mudah diklik.','','','',
'Perbaiki button.','return true;',
'kecil','touch','perbesar'),

('Spacing Tidak Konsisten',25,'UI/UX','Desain','Sulit','Debugging Zone',
'spacing harus konsisten.','','','',
'Perbaiki spacing.','return true;',
'tidak rata','margin padding','samakan'),

('Hierarchy Buruk',25,'UI/UX','Desain','Sulit','Debugging Zone',
'hierarchy penting.','','','',
'Perbaiki hierarchy.','return true;',
'semua sama','judul beda','atur ukuran'),

('Typography Buruk',25,'UI/UX','Desain','Sulit','Debugging Zone',
'font harus jelas.','','','',
'Perbaiki font.','return true;',
'sulit baca','font','ganti'),

('Terlalu Banyak Warna',25,'UI/UX','UI','Sulit','Debugging Zone',
'warna harus konsisten.','','','',
'Perbaiki warna.','return true;',
'berantakan','konsisten','batasi');
